"""
Django settings for shoes project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aox4o%4tozwb+!8-#o02huqbq(8+u&)$m0!2lz=sufmvkz6o_e'

# SECURITY WARNING: don't run with debug turned on in production!
# التعديل المطلوب
DEBUG = False


# التعديل المطلوب
ALLOWED_HOSTS = ['al-qathifi.com', 'www.al-qathifi.com', '127.0.0.1', 'localhost']




# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shoes_view',  # Our main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # For language switching
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shoes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # For internationalization
                'shoes_view.context_processors.cart_context',  # Custom context processor for cart
            ],
        },
    },
]

WSGI_APPLICATION = 'shoes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Make email optional for authentication
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "none"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'  # Default to Arabic
TIME_ZONE = 'Asia/Jerusalem'  # Middle East timezone

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Language settings for multi-language support
LANGUAGES = [
    ('ar', 'العربية'),  # Arabic
    ('en', 'English'),  # English
    ('he', 'עברית'),   # Hebrew
]

# Locale paths for translations
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Use RTL by default
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session settings for guest checkout
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Telegram integration settings (replaces WhatsApp)
TELEGRAM_BOT_TOKEN = '8445071189:AAHWcAWBpaoxwAlfrwSt6kqBLgSAwtp1wmk'  # Get from @BotFather on Telegram
TELEGRAM_CHAT_ID = '-1002706827089'      # Your channel or chat ID (e.g., -1001234567890 for channels)

# Site URL for Telegram image links
# التعديل المطلوب
SITE_URL = 'https://al-qathifi.com'


# Wheel of Fortune settings
DEFAULT_WHEEL_DISCOUNT = 5  # Default 5% discount

# Cache settings for performance
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Email settings (for order confirmations)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development
DEFAULT_FROM_EMAIL = 'noreply@alqadhafi-shoes.com'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''

# Currency settings
DEFAULT_CURRENCY = 'ILS'  # Israeli Shekel - adjust as needed
CURRENCY_SYMBOL = '₪'       # Set currency to shekels

# Libre Translate API settings
LIBRE_TRANSLATE_URL = 'https://libretranslate.de/translate'
LIBRE_TRANSLATE_API_KEY = None  # Set if using paid version

# Print settings
ENABLE_AUTO_PRINT = True
PRINTER_NAME = 'U80II(U)'  # Thermal printer model
PRINT_TIMEOUT = 30  # Seconds to wait for print completion
RECEIPT_WIDTH = 48  # Characters width for thermal printers (U80II standard)

# Additional printer settings for better compatibility
PRINT_DEBUG = True  # Set to False in production
PRINT_METHOD = 'thermal'  # Options: 'auto', 'notepad', 'direct', 'command', 'thermal'
ENABLE_PRINT_PREVIEW = False  # Show print preview dialog

# Thermal printer specific settings
THERMAL_PRINTER_PORT = 'auto'  # Auto-detect or specify like 'COM1', 'USB001', etc.
THERMAL_PRINTER_ENCODING = 'utf-8'  # Plain text encoding for thermal printers
THERMAL_CUT_PAPER = False  # Plain text mode - no cut commands
THERMAL_PRINT_LOGO = False  # Print store logo (if available)

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'shoes_view': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# Jazzmin settings - Professional Admin Dashboard
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "متجر القدفي للأحذية",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Al Qadhafi Shoes",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "القدفي",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": None,

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": False,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "مرحباً بك في لوحة التحكم",

    # Copyright on the footer
    "copyright": "Al Qadhafi Shoes 2025",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": ["auth.User", "shoes_view.Product"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "الصفحة الرئيسية",  "url": "admin:index", "permissions": ["auth.view_user"]},
        # external url that opens in a new window (Permissions can be added)
        {"name": "الموقع", "url": "/", "new_window": True},
        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "shoes_view"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "الموقع", "url": "/", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "shoes_view", "shoes_view.product", "shoes_view.order", "shoes_view.brand"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "shoes_view": [{
            "name": "تقارير المبيعات",
            "url": "/admin/custom/sales-report/",
            "icon": "fas fa-chart-line",
            "permissions": ["shoes_view.view_order"]
        }]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "shoes_view.Product": "fas fa-shoe-prints",
        "shoes_view.Brand": "fas fa-tags",
        "shoes_view.Order": "fas fa-shopping-cart",
        "shoes_view.Cart": "fas fa-shopping-basket",
        "shoes_view.Customer": "fas fa-user-circle",
        "shoes_view.ColorVariant": "fas fa-palette",
        "shoes_view.LoyaltyProgram": "fas fa-gift",
        "shoes_view.WheelResult": "fas fa-dharmachakra",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": True,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "admin/css/admin_layout.css",
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "single",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
     # Add a language dropdown into the admin
     "language_chooser": True,
}
