# Generated by Django 5.2 on 2025-07-08 10:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم العلامة التجارية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Brand Name (English)')),
                ('name_he', models.CharField(blank=True, max_length=100, verbose_name='Brand Name (Hebrew)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='شعار العلامة التجارية')),
                ('description', models.TextField(blank=True, verbose_name='وصف العلامة التجارية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رسالة التواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجائزة')),
                ('prize_type', models.CharField(choices=[('discount', 'خصم'), ('free_shipping', 'شحن مجاني'), ('no_prize', 'لا يوجد جائزة')], max_length=20, verbose_name='نوع الجائزة')),
                ('value', models.PositiveIntegerField(verbose_name='القيمة')),
                ('probability', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='الاحتمالية')),
                ('color', models.CharField(default='#FF0000', max_length=7, verbose_name='لون القطاع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'إعداد العجلة',
                'verbose_name_plural': 'إعدادات العجلة',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='مفتاح الجلسة')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('street_address', models.TextField(verbose_name='عنوان الشارع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رقم الطلب')),
                ('payment_method', models.CharField(choices=[('cash', 'الدفع عند الاستلام'), ('visa', 'فيزا')], max_length=10, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('confirmed', 'مؤكد'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الخصم')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ النهائي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('whatsapp_sent', models.BooleanField(default=False, verbose_name='تم إرسال واتساب')),
                ('printed', models.BooleanField(default=False, verbose_name='تمت الطباعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shoes_view.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Product Name (English)')),
                ('name_he', models.CharField(blank=True, max_length=200, verbose_name='Product Name (Hebrew)')),
                ('description', models.TextField(blank=True, verbose_name='وصف المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('sizes', models.JSONField(default=list, verbose_name='المقاسات المتاحة')),
                ('color', models.CharField(choices=[('black', 'أسود'), ('white', 'أبيض'), ('brown', 'بني'), ('blue', 'أزرق'), ('red', 'أحمر'), ('gray', 'رمادي'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('navy', 'كحلي'), ('beige', 'بيج')], max_length=20, verbose_name='اللون')),
                ('color_hex', models.CharField(default='#000000', max_length=7, verbose_name='كود اللون')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shoes_view.brand', verbose_name='العلامة التجارية')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='المقاس')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shoes_view.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes_view.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر الطلب',
                'verbose_name_plural': 'عناصر الطلبات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='الصورة')),
                ('color', models.CharField(choices=[('black', 'أسود'), ('white', 'أبيض'), ('brown', 'بني'), ('blue', 'أزرق'), ('red', 'أحمر'), ('gray', 'رمادي'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('navy', 'كحلي'), ('beige', 'بيج')], max_length=20, verbose_name='لون الصورة')),
                ('is_main', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='نص بديل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoes_view.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة المنتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('street_address', models.TextField(blank=True, verbose_name='عنوان الشارع')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('he', 'עברית')], default='ar', max_length=5, verbose_name='اللغة المفضلة')),
                ('newsletter_subscribed', models.BooleanField(default=False, verbose_name='مشترك في النشرة الإخبارية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='WheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='مفتاح الجلسة')),
                ('discount_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم الاستخدام')),
                ('spin_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدوران')),
                ('used_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheel_spins', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'دوران العجلة',
                'verbose_name_plural': 'دورانات العجلة',
                'ordering': ['-spin_date'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='المقاس')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes_view.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر السلة',
                'verbose_name_plural': 'عناصر السلة',
                'unique_together': {('user', 'product', 'size')},
            },
        ),
    ]
