# Generated by Django 4.2.5 on 2025-07-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_view', '0002_alter_cartitem_unique_together_cartitem_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم اللون')),
                ('hex_code', models.CharField(default='#FFFFFF', max_length=7, verbose_name='كود اللون')),
            ],
            options={
                'verbose_name': 'خيار اللون',
                'verbose_name_plural': 'خيارات الألوان',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swatch_image', models.ImageField(upload_to='products/swatches/', verbose_name='صورة اللون المصغرة')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes_view.coloroption', verbose_name='اللون')),
                ('display_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_variant_display', to='shoes_view.productimage', verbose_name='صورة العرض الرئيسية لهذا اللون')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='shoes_view.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'متغير لون المنتج',
                'verbose_name_plural': 'متغيرات ألوان المنتج',
                'ordering': ['color__name'],
                'unique_together': {('product', 'color')},
            },
        ),
    ]
