# Generated by Django 4.2.5 on 2025-07-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_view', '0003_coloroption_remove_product_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم اللون')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود اللون')),
                ('hex_color', models.CharField(default='#000000', max_length=7, verbose_name='كود اللون الهكس')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='colors/', verbose_name='صورة مصغرة للون')),
            ],
            options={
                'verbose_name': 'متغير اللون',
                'verbose_name_plural': 'متغيرات الألوان',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productcolorvariant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productcolorvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcolorvariant',
            name='display_image',
        ),
        migrations.RemoveField(
            model_name='productcolorvariant',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'أسود'), ('white', 'أبيض'), ('brown', 'بني'), ('blue', 'أزرق'), ('red', 'أحمر'), ('gray', 'رمادي'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('navy', 'كحلي'), ('beige', 'بيج')], max_length=20, null=True, verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(default='#000000', max_length=7, verbose_name='كود اللون'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'أسود'), ('white', 'أبيض'), ('brown', 'بني'), ('blue', 'أزرق'), ('red', 'أحمر'), ('gray', 'رمادي'), ('green', 'أخضر'), ('yellow', 'أصفر'), ('navy', 'كحلي'), ('beige', 'بيج')], max_length=20, null=True, verbose_name='لون الصورة'),
        ),
        migrations.DeleteModel(
            name='ColorOption',
        ),
        migrations.DeleteModel(
            name='ProductColorVariant',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='shoes_view.colorvariant', verbose_name='متغير اللون'),
        ),
    ]
