# Generated by Django 5.2 on 2025-07-13 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_view', '0004_colorvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelconfiguration',
            name='probability',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الاحتمالية'),
        ),
        migrations.CreateModel(
            name='WheelAdminControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='التحكم الافتراضي', max_length=100, verbose_name='اسم التحكم')),
                ('control_mode', models.CharField(choices=[('random', 'عشوائي (حسب الاحتمالية)'), ('force_prize', 'فرض جائزة معينة'), ('force_no_prize', 'فرض عدم وجود جائزة'), ('sequence', 'تسلسل محدد')], default='random', max_length=20, verbose_name='نمط التحكم')),
                ('sequence_prizes', models.JSONField(blank=True, default=list, verbose_name='تسلسل الجوائز')),
                ('current_sequence_index', models.PositiveIntegerField(default=0, verbose_name='فهرس التسلسل الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('forced_prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes_view.wheelconfiguration', verbose_name='الجائزة المفروضة')),
            ],
            options={
                'verbose_name': 'تحكم إداري في العجلة',
                'verbose_name_plural': 'تحكم إداري في العجلة',
                'ordering': ['-updated_at'],
            },
        ),
    ]
