# Generated by Django 5.2 on 2025-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_view', '0005_alter_wheelconfiguration_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelconfiguration',
            name='can_win',
            field=models.BooleanField(default=True, verbose_name='يمكن الفوز بها'),
        ),
    ]
