# Generated by Django 5.2 on 2025-07-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_view', '0006_wheelconfiguration_can_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelconfiguration',
            name='gift_description',
            field=models.TextField(blank=True, help_text='وصف تفصيلي للهدية (مطلوب فقط لنوع الهدية)', verbose_name='وصف الهدية'),
        ),
        migrations.AddField(
            model_name='wheelspin',
            name='gift_description',
            field=models.TextField(blank=True, verbose_name='وصف الهدية'),
        ),
        migrations.AddField(
            model_name='wheelspin',
            name='prize_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الجائزة'),
        ),
        migrations.AddField(
            model_name='wheelspin',
            name='prize_type',
            field=models.CharField(default='discount', max_length=20, verbose_name='نوع الجائزة'),
        ),
        migrations.AlterField(
            model_name='wheelconfiguration',
            name='prize_type',
            field=models.CharField(choices=[('discount', 'خصم'), ('free_shipping', 'شحن مجاني'), ('gift', 'هدية'), ('no_prize', 'لا يوجد جائزة')], max_length=20, verbose_name='نوع الجائزة'),
        ),
    ]
