# Generated by Django 5.2 on 2025-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_view', '0007_wheelconfiguration_gift_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wheel_free_shipping',
            field=models.BooleanField(default=False, verbose_name='شحن مجاني من العجلة'),
        ),
        migrations.AddField(
            model_name='order',
            name='wheel_gift_description',
            field=models.TextField(blank=True, verbose_name='وصف الهدية من العجلة'),
        ),
        migrations.AddField(
            model_name='order',
            name='wheel_gift_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الهدية من العجلة'),
        ),
    ]
