# Generated by Django 5.2 on 2025-07-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_view', '0008_order_wheel_free_shipping_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', '?'], 'verbose_name': 'صورة المنتج', 'verbose_name_plural': 'صور المنتجات'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
    ]
