# Generated by Django 5.2 on 2025-07-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_view', '0009_alter_productimage_options_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
