# Generated by Django 4.2.23 on 2025-07-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_view', '0010_remove_contactmessage_email_remove_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'الدفع عند الاستلام')], max_length=10, verbose_name='طريقة الدفع'),
        ),
    ]
